name: "Release"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment"
        options:
          - "staging"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "corretto"
          cache: "sbt"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region:     ap-northeast-1
          role-to-assume: 'arn:aws:iam::415821524965:role/deploy-github-actions'

      - name: Build scala & publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
        run: sbt "release with-defaults"
